### ISSUE TITLE
[iOS] Memory leak during live reloads

### ISSUE THREAD

**Issue by kristfal** [react-native-mapbox-gl/maps#383] opened 2019-09-13 09:57 UTC
**Describe the bug**
Live reloads seem to retain old map instances, causing memory leaks.

**To Reproduce**
Launch a MapView and live reload multiple times. Xcode debugger will show memory usage climbing.

**Expected behavior**
Memory should not be retained.

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: N/A
 - OS: 12
 - SDK Version: Latest
 - React Native Version: 0.59.X

**Additional context**
This may also be affecting multiple map views.

**Comment by muthenberg** [comment] 2019-09-19 07:31
Same problem here. It took us quite some time, to figure out that this was not a memory leak within our code but seems to result from mapbox.

**Comment by anttijva** [comment] 2019-10-25 08:59
Any news on this?

**Comment by anttijva** [comment] 2019-12-24 11:11
Not stale.

**Comment by anfriis** [comment] 2020-02-22 13:17
Still an issue

**Comment by mfazekas** [comment] 2020-04-08 14:18
I've tried to repro the issue with our example app which is RN 0.62.1. Using `Fast Refresh` i was not able to increase memory useage significantly. In the menu it's using about 170MB, if i open a view with map it goes up to 300 MB, but i doesn't not grow for refresh, and returns to  original if i go back to the menu.

I was able to reproduce small memory increase when going back to the menu then opening a map but that was about 1MB  increase by opening then closing the map. But that leak seems to be coming from RCTMGLImageQueueOperation, and i don't think it's related to fast refresh. I'll fix the leak to RCTMGLImageQueueOperation.

**Closed** 2020-04-08 20:37 UTC
Labels: Needs: Author Feedback, Needs: Repro

**Comment by prinse1545** [comment] 2020-07-02 01:42
I am encountering this issue as well...please open it back up

**Comment by mfazekas** [comment] 2020-07-02 03:34
@prinse1545 pls add details so we can look into it. Include RN and rn-mapbox versions, the magnitude of leak you observe (MB/refresh), and ideally a standalone component and description how to reproduce it.

**Comment by dorthwein** [comment] 2020-10-07 16:05
This seems pretty straight forward to reproduce - 

- Create a map
- Add a Shape View with a line string
- Press cmd+R 
- Watch memory grow!

RN: 0.63.3
ReactNativeMapbox: 8.1.0-rc.5

**Comment by mfazekas** [comment] 2020-10-07 16:22
@dorthwein pls also document the amount of memory growth you're seeing. https://github.com/react-native-mapbox-gl/maps/issues/383#issuecomment-652761716

**Comment by systemlevel** [comment] 2020-12-16 18:36
@mfazekas When you use RN Mapbox in your simulator is your map slow as you pan around? Ours is sluggish but I'm not sure if that's to be expected or not.

**Comment by newtracs** [comment] 2021-08-13 13:13
Im experiencing this also.  On latest Mapbox IOS SDK and react-native-mapbox-maps version.

**Comment by tomgreco** [comment] 2021-10-09 23:13
I have this issue as well. Latest iOS SDK. RN v0.64.
Latest version of react-native-mapbox-gl.
