### ISSUE TITLE
userTrackingMode FollowWithCourse does not consider minDisplacement

### ISSUE THREAD

**Issue by kneubuehl** [react-native-mapbox-gl/maps#1505] opened 2021-08-25 04:21 UTC
We are building an app for driving directions and navigation. We want to use userFollowMode = "course" to orient the map in the direction of the device's movement.

This works fine when the device is in motion, for example when walking briskly or when in a vehicle driving. However when the device is stationary, the map spins due to extremely small GPS measurements each second.

The minDisplacement parameter is meant to limit GPS updates to a given threshold of movement. We have tested with various thresholds. It appears that minDisplacement works properly in limiting updates to coordinates.

However the FollowWithCourse mode seems to separately consider continuous GPS updates, causing the map orientation to spin when the device is near stationary, due to the noise in the GPS signal.

The FollowWithCourse mode should consider minDisplacement to limit updates to the Camera orientation, only adjusting the orientation with major GPS updates rather than continuous minor updates to prevent spinning.

Below is sample code where you can adjust the minDisplacement value with GPS update logs printed to the screen. The map will spin when the device is stationary, even with the minDisplacement is set at a higher value such as 10.

```
const MapScreen = ({}) => {
  const [currentCoords, setCurrentCoords] = useState({})
  const handleOnUpdate = (feature) => {
    setCurrentCoords(feature)
  }
  return (
    <SafeAreaView style={styles.container}>
      <MapboxGL.MapView
        style={styles.map}
        tintColor={'red'}
        compassEnabled={true}>
        <MapboxGL.Camera followUserLocation={true} followUserMode={'course'} />
        <MapboxGL.UserLocation
          renderMode={'normal'}
          showsUserHeadingIndicator={true}
          androidRenderMode={'normal'}
          minDisplacement={0}
          onUpdate={handleOnUpdate}
        />
      </MapboxGL.MapView>
      <Text style={{ backgroundColor: 'gray' }}>
        {JSON.stringify(currentCoords)}
      </Text>
    </SafeAreaView>
  )
}
```

-Occurs on both Android and iOS platforms
-react-native-mapbox-gl version: 8.1.0
-react-native version: 0.63.3

**Comment by kobagapu** [comment] 2021-09-07 06:29
Hi @kneubuehl ###  _when using above current location is also not getting please help_

 <MapboxGL.MapView
        style={styles.map}
      >
        <MapboxGL.Camera
         followUserLocation={true} 
         followUserMode={'course'} />
        <MapboxGL.UserLocation
          renderMode={'normal'}
          showsUserHeadingIndicator={true}
          androidRenderMode={'normal'}
          minDisplacement={0}
          onUpdate={handleOnUpdate}
        />
      </MapboxGL.MapView>

**Comment by dorthwein** [comment] 2021-09-22 15:11
We are running into this as well unfortunately but we only see it happening on Android. 

We additionally use react-native-background-geolocation which could be overriding GPS update frequencies from Mapbox's internal updates on iOS preventing the issue on iOS but having it happen on Android.

**Comment by kneubuehl** [comment] 2021-09-22 15:29
Our company may be willing to commit funding support for this issue. If anyone is interested, @ferdicus especially, please let me know here and a way to make further contact.

**Comment by dorthwein** [comment] 2021-09-29 17:34
Adding this issue I found on the native SDK issues commenting on this issue. 

https://github.com/mapbox/mapbox-gl-native-android/issues/41

**Comment by dorthwein** [comment] 2021-09-29 18:21
So steps to resolve this seem to be that we need to filter location updates at the LocationEngine level and add some consideration for min displacement here.  

I'd be curious if we could just bolt on the mapbox navigation location engine filtering mentioned in mapbox/mapbox-gl-native-android#41

**Comment by dorthwein** [comment] 2021-09-29 20:24
So I've identified that the LocationComponentManager.java attempts to separate the user location requests and the camera location request.  This is where we can access the correct location component.

Docs: https://docs.mapbox.com/android/maps/api/9.6.0/com/mapbox/mapboxsdk/location/LocationComponent.html

TBD how to actually address the issue though.

**Comment by dorthwein** [comment] 2021-10-04 18:19
I've hit a dead end due to my lack of Java knowledge.  We'd be willing to contribute for a fix with this as well.

**Comment by dorthwein** [comment] 2021-10-06 15:22
Ok - so here is a work around we came up with.  Basically there are 2 pitfalls.  When in a dev mock location environment, setting followLocationMode to "compass" does not follow the mocked location, and instead follows the real devices actual compass.  When working on this problem, this would lead us to believe there was bad behavior, but i was actually correct behavior.  Further more, this would behave oddly in an iOS simulator and iOS in general when using followUserMode course works as intended!  Several lessons learned here but this is the work around we came up with that covers our navigation use-case in terms of dealing with Android Spinning issue. 

For us followUserMode is set by user options

**Big take away is that on android, when stopped, instead of followUserMode course use compass!**

```
  const isStopped = speed < 3.0
  return (
    <MapboxGL.Camera
      heading={cameraHeading}
      pitch={pitch}
      zoomLevel={zoomLevel}
      followPitch={pitch}
      followZoomLevel={zoomLevel}
      defaultSettings={finishedInitialLoadingStyle ? undefined : defaultSettings}
      followUserMode={
        Platform.OS == "android" && isStopped && followUserMode == "course"
          ? "compass"
          : followUserMode
      }
      followUserLocation={!ready ? true : !!followUserLocation || false}
      animationMode={animationMode}
      animationDuration={animationDuration}
      centerCoordinate={noCenterCoordinate ? null : centerCoordinate}
      bounds={bounds}
    />
```

**Comment by kneubuehl** [comment] 2021-10-06 23:48
Thank you @dorthwein it's an interesting workaround. We're still looking for support on the root cause in this case since the user often has the phone in hand and it's not always positioned directionally forward in relation to the car.

**Comment by ferdicus** [comment] 2021-11-17 17:15
With the limited time of the maintainers I'd close this as "resolved" with the work-around.  
Feel free to drop a comment if you'd like this to be re-opened.

**Closed by ferdicus** 2021-11-17 17:15 UTC
Labels: help wanted
