### ISSUE TITLE
Heading indicator (normal) not following map rotation

### ISSUE THREAD

**Issue by mzu** [react-native-mapbox-gl/maps#1023] opened 2020-09-10 12:07 UTC
**Describe the bug**
The following happens when running the example project on a device for iOS: The heading indicator (arrow) is not following when the map gets rotated manually. It keeps on pointing towards the same direction as if the map was still orientated due north.

**To Reproduce**
- Install the **example app** for the latest release (I used tag 8.1.0-rc4). Then Camera->Set User Tracking Modes->Toggle heading indicator: true, Toggle User Location: true. 
- Rotate the map and and the heading indicator will not follow along

**Note:** It does work the correct way if `UserLocation.renderMode={'native'}`

**Example**
This also happens with *your* example here: [ SetUserTrackingModes.js](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/SetUserTrackingModes.js)

**Expected behavior**
The heading indicator for UserLocation.renderMode={'normal'} should follow the MapView rotation the same way as it does for UserLocation.renderMode={'native'}

**Versions (please complete the following information):**
 - Platform: iOS
 - Device: iPhone11
 - Emulator/ Simulator: no
 - OS: iOS13.7
 - react-native-mapbox-gl Version 8.1.0-rc4
 - React Native Version 0.63.2

**Comment by SalihZinaty** [comment] 2020-09-10 12:51
where you define the UserLocation.renderMode={'native'} ? on the componentdidmount ?

**Comment by ferdicus** [comment] 2020-09-10 13:23
will reopen when description is edited accordingly

**Comment by mzu** [comment] 2020-11-05 13:33
Here is a [video](https://youtu.be/_7SjzUW52YA) to illustrate the problem. The 'normal' heading indicator gets 'out of sync' when the map view gets rotated. Compare with the correct heading of the 'native' heading indicator.

**Comment by ferdicus** [comment] 2020-11-05 15:54
So, wait, the issue is, that the normal location indicators heading icon is following the map rotation (not device rotation).
That is the issue, right? 

Just for clarifications sake:
I should point in the direction the user is heading towards. In the best case the user should be moving in order to get a heading.
The heading should _NOT_ change with the rotation of the map, if anything maybe with the rotation of the device.

**Comment by systemlevel** [comment] 2020-11-05 16:18
@mzu we ran into the same issue. You can get the orientation of the map on region change. To get the correct compass orientation in degrees, you can just merely minus that from the current compass rotation and it will offset the rotation of the map.

**Comment by mzu** [comment] 2020-11-05 17:22
@ferdicus:
>So, wait, the issue is, that the normal location indicators heading icon is following the map rotation (not device rotation).

The problem is that the heading arrow is **currently not** following the map rotation (gesture) while the physical device keeps on pointing in the same direction.

> I should point in the direction the user is heading towards
>The heading should NOT change with the rotation of the map, if anything maybe with the rotation of the device.

Not sure about that. I think the heading arrow should point to where the device is pointing. The direction of travel in the real world should stay in line with the direction of travel on the map.

There is a good reason why:
1. I am on a mountain. I am standing in front of a cliff. Visibility is near zero. I do not want to start moving in order to figure out if I am 'heading' away from the cliff! The heading arrow should point where the device is pointing. Which works until you start rotating the map in 'normal' mode!

2. If 1. is true then the heading arrow needs to follow the map rotation gesture. Otherwise I can move the cliff behind me on the map (rotation gesture) while in the real world it's still in front of me (ouch). **It needs to keep on pointing towards the cliff on the map if I do not move at all and only the rotation gesture is happening.** 

@systemlevel: Good idea, I just think switching between 'normal' and 'native' mode should result in the same behaviour?

MaybeI am confused and the way I see  it would break other cases. This is how it looks like in native mode on iOS which is what I would expect: [video](https://youtu.be/ClPsxTQ6te0).

**Comment by jaltin** [comment] 2021-02-09 10:46
We have made a PR to fix this: https://github.com/react-native-mapbox-gl/maps/pull/1215

**Comment by ferdicus** [comment] 2021-02-12 13:38
resolved via #1215

**Closed by ferdicus** 2021-02-12 13:38 UTC
Labels: iOS
