### ISSUE TITLE
Layer can't be mounted more than once

### ISSUE THREAD

**Issue by chrisparton1991** [react-native-mapbox-gl/maps#571] opened 2019-12-16 01:09 UTC
**Describe the bug**
Conditionally rendering a layer works fine the first time, but the layer fails to re-appear on subsequent mounts.

**To Reproduce**
Run the code snippet below with an appropriate `STYLE_URL` and `LAYER_ID` configured.

**Expected behavior**
1. Tapping 'Enable' should cause the layer to appear [PASS]
2. Tapping 'Disable' should cause the layer to disappear [PASS]
3. Tapping 'Enable' again should cause the layer to reappear **[FAIL]**

**Screenshots**
Here's a 10 second video: https://imgur.com/a/Eg5StBn

**Versions (please complete the following information):**
 - Platfrom: Android and iOS
 - Device: Samsung Galaxy S7, iPad Air 3 simulator
 - OS: Android 7.1.1, iOS 13.2.2
 - SDK Version `minSdkVersion` = 21, `targetSdkVersion` = 28
 - React Native Version: 0.61.5

**Additional context**
Minimal reproducible sample:
```
const STYLE_URL = 'mapbox://styles/YOUR_ID/YOUR_STYLE_ID'
const LAYER_ID = 'YOUR_LAYER'

const TestMap = () => {
  const [enabled, setEnabled] = useState(false)
  const toggle = useCallback(() => {
    setEnabled(!enabled)
  }, [enabled])

  return (
    <View style={{width: 300, margin: 50}}>
      <Button onPress={toggle} title={enabled ? 'Disable' : 'Enable'} />
      <MapboxGL.MapView styleURL={STYLE_URL} style={{ width: 300, height: 300 }}>
        <MapboxGL.Camera />

        {enabled && (
          <MapboxGL.RasterLayer id={LAYER_ID} style={{ visibility: 'visible' }} />
        )}
      </MapboxGL.MapView>
    </View>
  )
}
```

**Comment by lrpinto** [comment] 2020-01-29 15:43
Hi, I just stumbled on this one looking for something different... but looking at the code I am thinking you may need to change the visibility to 'none', since that is a property that might need to go back to the style. Did you try that?

**Comment by chrisparton1991** [comment] 2020-02-04 23:33
@lrpinto thanks for the suggestion. I ended up adding every possible layer to the map, and I'm controlling the visibility instead of adding/removing layers. That seems to perform fine, though it wouldn't be a feasible solution for everyone.

I'm happy for this to be closed as it's no longer an issue for me, but it might be worth keeping open as it's still a valid bug in my mind.

**Comment by mfazekas** [comment] 2020-02-19 20:03
I was not able to reproduce the issue.
I've modified example: [WatercolorRasterTiles](https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/WatercolorRasterTiles.js)

like this:
```es6
import React from 'react';
import {View, StyleSheet, Button} from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';
import {Slider} from 'react-native-elements';

import sheet from '../styles/sheet';
import colors from '../styles/colors';
import {SF_OFFICE_COORDINATE} from '../utils';

import Page from './common/Page';
import BaseExamplePropTypes from './common/BaseExamplePropTypes';

const styles = StyleSheet.create({
  slider: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    maxHeight: 60,
    paddingHorizontal: 24,
  },
});

class WatercolorRasterTiles extends React.Component {
  static propTypes = {
    ...BaseExamplePropTypes,
  };

  constructor(props) {
    super(props);

    this.state = {
      opacity: 1,
      enabled: true,
    };

    this.onOpacityChange = this.onOpacityChange.bind(this);
  }

  onOpacityChange(value) {
    this.setState({opacity: value});
  }

  render() {
    const rasterSourceProps = {
      id: 'stamenWatercolorSource',
      tileUrlTemplates: [
        'https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg',
      ],
      tileSize: 256,
    };
    const {enabled} = this.state;

    return (
      <Page {...this.props}>
        <MapboxGL.MapView style={sheet.matchParent}>
          <MapboxGL.Camera
            zoomLevel={16}
            centerCoordinate={SF_OFFICE_COORDINATE}
          />

          <MapboxGL.RasterSource {...rasterSourceProps}>
            {enabled && (
              <MapboxGL.RasterLayer
                id="stamenWatercolorLayer"
                sourceID="stamenWatercolorSource"
                style={{rasterOpacity: this.state.opacity}}
              />
            )}
          </MapboxGL.RasterSource>
        </MapboxGL.MapView>

        <View style={styles.slider}>
          <Slider
            value={this.state.opacity}
            onValueChange={this.onOpacityChange}
            thumbTintColor={colors.primary.blue}
            thumbTouchSize={{width: 44, height: 44}}
            maximumTrackTintColor={colors.secondary.purpleLight}
            minimumTrackTintColor={colors.secondary.purpleDark}
          />
          <Button
            title={enabled ? 'disable' : 'enable'}
            onPress={() => {
              this.setState({enabled: !enabled});
            }}
          />
        </View>
      </Page>
    );
  }
}

export default WatercolorRasterTiles;
```


![rasterlayer](https://user-images.githubusercontent.com/52435/74871136-3f754200-535b-11ea-8a7a-7ab331cc59b5.gif)

**Comment by mfazekas** [comment] 2020-02-19 20:04
I'm closing this, please complain if the issue still persist with the current branch

**Closed by mfazekas** 2020-02-19 20:04 UTC
