### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'location.coords') with react native function components

### ISSUE THREAD

**Issue by prox2** [react-native-mapbox-gl/maps#1236] opened 2021-02-25 06:02 UTC
**Describe the bug**  
`OnUpdate` prop in `<MapboxGL.UserLocation` doesn't pass any `coords` when user location updated using react native function components as with react native class components everything working fine 

**To Reproduce**  
on  `UserLocation` component  `onUpdate` prop pass function onUserLocationUpdate() 

Example:
```
import React, { useEffect, useState, useRef } from 'react';
import MapboxGL from '@react-native-mapbox-gl/maps';


const app = () => {

 const [latitude, setlatitude] = useState(0.0);
    const [longitude, setlongitude] = useState(0.0);
    const [altitude, setaltitude] = useState(0.0);

const onUserLocationUpdate = async (location) => {
        //console.log(location)
        let lat = location.coords.latitude;
        let long = location.coords.longitude;
        let alt = location.coords.altitude;
        setlatitude(lat)
        setlongitude(long)
        setaltitude(alt)
} 

    return (
         <MapboxGL.MapView          
          surfaceView={true}
          zoomLevel={15}
          logoEnabled={false}
          style={styles.matchParent}>

           <MapboxGL.UserLocation
                visible={true}
                onUpdate={() => onUserLocationUpdate()}
            />

            <MapboxGL.Camera
                followZoomLevel={17} 
               //followUserLocation
                followUserMode={'normal'}
                followUserLocation={true}
                followZoomLevel={17}
                animationDuration={1000}
            />


     </MapboxGL.MapView>
    );
  }
}
```

**Expected behavior**  
the current `coords` should be updated and passed to the function

**Actual behavior**  
It throw this error:  `ERROR    TypeError: undefined is not an object (evaluating 'location.coords')`

**Versions:**  
 - Platform: [ Android]
 - Platform OS: [Android 9]
 - Device: [HUAWEI Mate 8]
 - Emulator/ Simulator: [no]
 - Dev OS: [ Win10]
 - react-native-mapbox-gl Version [8.1.0]
 - React Native Version [0.63.4]

**Comment by mzu** [comment] 2021-02-25 07:48
Try this instead:
```
           <MapboxGL.UserLocation
                visible={true}
                onUpdate={(location) => onUserLocationUpdate(location)}
            />
```

**Comment by prox2** [comment] 2021-02-25 08:05
I tried this way and still getting same error, when i console.log(location) inside function `onUserLocationUpdate(location)` after it passed it give something like this:

`{"coords": {"accuracy": 46.196998596191406, "altitude": 46.768879368492335, "heading": 4.40336799621582, "latitude": 42.649301, "longitude": 12.484028, "speed": 0.9461610317230225}, "timestamp": 1614240076053}` 
so if you want to get `latitude` value I will do something like this: `location.coords.latitude` but when I do it it give same error

**Comment by prox2** [comment] 2021-02-25 08:05
> Try this instead:
> 
> ```
>            <MapboxGL.UserLocation
>                 visible={true}
>                 onUpdate={(location) => onUserLocationUpdate(location)}
>             />
> ```

 I tried this way and still getting same error, when i console.log(location) inside function `onUserLocationUpdate(location)` after it passed it give something like this:

`{"coords": {"accuracy": 46.196998596191406, "altitude": 46.768879368492335, "heading": 4.40336799621582, "latitude": 42.649301, "longitude": 12.484028, "speed": 0.9461610317230225}, "timestamp": 1614240076053}` 
so if you want to get `latitude` value I will do something like this: `location.coords.latitude` but when I do it it give same error

**Comment by mzu** [comment] 2021-02-25 08:30
```
{"coords": {"accuracy": 46.196998596191406, "altitude": 46.768879368492335, "heading": 4.40336799621582, "latitude": 42.649301, "longitude": 12.484028, "speed": 0.9461610317230225}, "timestamp": 1614240076053}
```

is what you want. I don't see a problem with accessing `location.coords.latitude`. `location` should never be empty or `null`. As far as I know you will get the last known location. Maybe add a `null` check for `location.coords` at the top of `onUserLocationUpdate()` and log how often you run into this compared to actually `receiving` the coords?

**Comment by ferdicus** [comment] 2021-02-25 09:17
@prox2, please see this PR #1203 

prior to it, `onUpdate` would misfire without an actual location (probably the cause of your issue).

if you can't update to the commit of the PR or the current `master` then you should include some check in your `onUpdate` callback that verifies for `coords` on `location` before processing it


Closing

**Closed by ferdicus** 2021-02-25 09:17 UTC
