### ISSUE TITLE
About React Native Mapbox GL Demo

### ISSUE THREAD

**Issue by valuecreation** [react-native-mapbox-gl/maps#708] opened 2020-03-09 15:48 UTC
https://github.com/react-native-mapbox-gl/maps/tree/master/example
About installing.

/Users/kamiya/Projects/maps/example/ios

Will cause an error in pod install.
Do you know what?

```c
KamiyanoMacBook-Pro:ios kamiya$ pod install
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '/Users/kamiya/Projects/maps/example/ios/undefined'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

[!] Invalid `Podfile` file: 785: unexpected token at ''.

 #  from /Users/kamiya/Projects/maps/example/ios/Podfile:43
 #  -------------------------------------------
 #    end
 >    use_native_modules!
 #  end
 #  -------------------------------------------

```

**Comment by mfazekas** [comment] 2020-03-09 16:05
What is `pod --version`?

Not sure why do you have `.js` code exec tued for `pod install` it should be a ruby script

**Comment by mfazekas** [comment] 2020-03-09 16:06
Closing, will repoen if furher info suggests its a bug

**Closed by mfazekas** 2020-03-09 16:06 UTC

**Comment by valuecreation** [comment] 2020-03-10 16:33
This is version.
```
kamiyanoMacBook-Pro:ios kamiya$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
KamiyanoMacBook-Pro:ios kamiya$ gem -v
2.6.11
KamiyanoMacBook-Pro:ios kamiya$ pod --version
1.9.0
```

**Comment by mfazekas** [comment] 2020-03-10 19:15
Can you try `pod install --verbose`

**Comment by mfazekas** [comment] 2020-03-11 05:11
Also `react-native --version` you might not have react-native properly installed

**Comment by tkamiya0625** [comment] 2020-03-12 11:16
Thank you very much.
solved!

The cause may have been executing yarn add@react-native-mapbox-gl/maps in maps directory.
