### ISSUE TITLE
ShapeSourceRef.current.getClusterExpansionZoom is not a function

### ISSUE THREAD

**Issue by natedx** [react-native-mapbox-gl/maps#1349] opened 2021-05-15 22:39 UTC
**Describe the bug** 
getClusterExpansionZoom method on ShapeSource doesn't seem to exist.

**To Reproduce**  
Steps to reproduce the behavior. 

- Clone a test project that uses ShapeSource, like this one : https://github.com/react-native-mapbox-gl/maps/blob/master/example/src/examples/SymbolCircleLayer/ShapeSource.tsx
- Enable clustering and test the method using the code given in the #1279 push request:

```
const source = React.useRef(null);

...

<MapboxGL.ShapeSource
  ref={source}
  onPress={async (e) => {
    const feature = e.features[0];
    if (feature.properties?.cluster) {
      const zoom = await source.current.getClusterExpansionZoom(
        feature.properties.cluster_id,
      );
      // use zoom
    }
  }}
  cluster
  clusterMaxZoomLevel={13}
  clusterRadius={40}
/>
```

**Expected behavior**  
The method should return the zoom value.

**Actual behavior**  
Error message : `ShapeSourceRef.current.getClusterExpansionZoom is not a function.`

**Versions (please complete the following information):**  
 - Platform: Android, iOS
 - Platform OS: Android 10, iOS 14
 - Device: OnePlus6T, iPhoneX 
 - Emulator/ Simulator: no
 - Dev OS: OSX 11.3
 - react-native-mapbox-gl Version : 8.0.1
 - mapbox/mapbox-sdk Version : 0.11.0
 - React Native Version : 0.63.4

**Comment by LukeLaScala** [comment] 2021-05-16 07:20
Hey I figured this one out. The issue is more of a documentation error. The `getClusterExpansionZoom` method is only on the current beta build, not on 8.0.1. After upgrading to beta it was working fine

**Comment by ferdicus** [comment] 2021-05-16 13:34
Closing

**Closed by ferdicus** 2021-05-16 13:34 UTC
