### ISSUE TITLE
How to run the Examples?

### ISSUE THREAD

**Issue by renege** [react-native-mapbox-gl/maps#668] opened 2020-02-14 15:15 UTC
Hello,

How can I even open the Examples and run them separately  to see what each component does?

**Comment by ShaharyarMaroof** [comment] 2020-02-14 16:24
hey @renege 
1. Clone the repo
2. Go to the examples directory
3. run ```npm install``` then ```cd ios && pod install```
4. run ```cd ..``` and then run ```react-native run-ios```

**Comment by renege** [comment] 2020-02-14 16:47
@ShaharyarMaroof hello, then i got this: 
![Schermafdruk 2020-02-14 16 54 52](https://user-images.githubusercontent.com/2900069/74550651-08192680-4f52-11ea-9ccb-0d5d7501ce46.png)

**Comment by ShaharyarMaroof** [comment] 2020-02-14 16:50
complete link to run example project: https://github.com/react-native-mapbox-gl/maps/tree/master/example

Create a file called accesstoken in the root of the example project and just paste in your Mapbox access token. (The accesstoken file is processed in postinstall, so you need to run npm install after adding/changing accesstoken.)

Install our dependencies using npm install.

**Comment by renege** [comment] 2020-02-14 17:00
@ShaharyarMaroof 
Then it still it not working like it should. Material Icons not recognized. 
![BNMh-WXA](https://user-images.githubusercontent.com/2900069/74551630-d5702d80-4f53-11ea-86e8-95928f6648bf.png)

**Comment by ShaharyarMaroof** [comment] 2020-02-14 17:01
you can ```Dismiss (ESC)``` this error, and the app will be working.
I am also getting this error, but I can go through the examples.

**Comment by renege** [comment] 2020-02-14 17:02
So this is a bug, right?

**Comment by ShaharyarMaroof** [comment] 2020-02-14 17:03
I think some issue in the react-native-elements package, but we can still go through the examples. :)

**Comment by ferdicus** [comment] 2020-02-18 15:16
Guys, I can't reproduce this behaviour with the current master. 
I get a warning about `componentWillReceiveProps` deprecation - that's all.

![screenshot device-LMQ61075NFY9QCIREU 20-02-18_16:14:32](https://user-images.githubusercontent.com/26439946/74749088-e974a180-5269-11ea-9be9-7f2b6a71a8f4.png)


Besides that works as expected - here `Fly To`
![screenshot device-LMQ61075NFY9QCIREU 20-02-18_16:14:32](https://user-images.githubusercontent.com/26439946/74749184-0dd07e00-526a-11ea-81a0-c891f1729d89.png)


Closing

**Closed by ferdicus** 2020-02-18 15:16 UTC

**Comment by mfazekas** [comment] 2020-02-18 15:25
@ferdicus i think this was an iOS only issue. Should be addressed  by #674
