### ISSUE TITLE
7.0.10 crashing on start

### ISSUE THREAD

**Issue by ivpusic** [react-native-mapbox-gl/maps#635] opened 2020-01-22 16:10 UTC
**Describe the bug**

app crashes on start

```
 Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
```

**To Reproduce**

install version 7.0.10 and try to start the app

**Expected behavior**

does not crash

**Versions (please complete the following information):**
 - Platfrom: iOS
 - Device: iPhone 11
 - React Native Version: 0.61

**Comment by kristfal** [comment] 2020-01-22 16:28
Published 7.0.10 now. Can you try again?

**Comment by aemdy** [comment] 2020-01-22 16:39
The same issue. It is version 7.0.10 that is crashing the app immediately after it is launched.

**Comment by kristfal** [comment] 2020-01-22 16:40
Likely root cause at
https://github.com/mapbox/mapbox-gl-native-ios/issues/131

We’ll need to update download path and republish. I’ll do it tonight.

**Comment by kristfal** [comment] 2020-01-22 22:33
Ok, that was a bigger issue than expected. I think I fixed it.

Can you try https://github.com/react-native-mapbox-gl/maps/pull/637 ?

To install it, do `yarn add https://github.com/react-native-mapbox-gl/maps.git#update-ios-framework`

**Comment by kristfal** [comment] 2020-01-23 08:10
Merged this into master, you can install by `yarn add https://github.com/react-native-mapbox-gl/maps.git`

**Comment by makozlo-airship** [comment] 2020-01-23 18:01
I'm also having the crash-on-start issue using `7.2.0`. 

Steps to reproduce:
1. run `yarn add @react-native-mapbox-gl/maps`
2. run the project from Xcode
3. get an `abort with payload` error in Xcode that won't allow the build to continute running.

**Comment by jeveloper** [comment] 2020-01-23 19:26
@makozlo-airship Is this still happening for you? Or figure it out.

**Comment by kristfal** [comment] 2020-01-23 19:48
Make sure you unlink existing FW and use pods to install the new version @makozlo-airship 

Please try that and get back to me if the issue persists.

**Comment by makozlo-airship** [comment] 2020-01-23 22:55
@kristfal I did a clean install...I think I might be confused about installation. I'm using RN version `0.61.5` - I shouldn't have to do anything other than `yarn add @react-native-mapbox-gl/maps`, right?

**Comment by systemlevel** [comment] 2020-01-24 00:17
@makozlo-airship did you also `pod install` In your iOS directory?

**Comment by cglacet** [comment] 2020-01-24 09:10
I have the same issue (app crashing on start) with the following error:

```sh
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /Users/cglacet/Library/Developer/CoreSimulator/Devices/7CBB4959-C16B-4A17-BA68-7BBE7A046BBE/data/Containers/Bundle/Application/724057ED-70A3-49DB-A407-7014EA21EA80/AppName.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found
```

My dependencies are: 

```json
"@react-native-mapbox-gl/maps": "^7.0.10",
"@mapbox/geo-viewport": "^0.2.2",
"@mapbox/mapbox-sdk": "^0.6.0",
"@mapbox/polyline": "^1.0.0",
```

My config is the following: 
```sh
$ npx react-native info
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 88.09 MB / 16.00 GB
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.3.2 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5977832
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
```

I ran both `npm install` and `pod install` without any error showing up.

**Comment by kristfal** [comment] 2020-01-24 09:11
Please update to 7.2.0 and redo installation. Does it work now?

**Comment by cglacet** [comment] 2020-01-24 09:15
Currently trying it, so far I've ran: 

```bash
$ yarn add https://github.com/react-native-mapbox-gl/maps.git#update-ios-framework
$ cd ios 
$ pod install
...
Installing Mapbox-iOS-SDK (5.6.1)
Installing MapboxMobileEvents (0.10.2)
Installing react-native-mapbox-gl 7.2.0 (was 7.0.10)
...
```

I'll update this as I go.

**Comment by kristfal** [comment] 2020-01-24 12:09
@cglacet can you try to run the example? Eg:

1) Clone repo
2) `cd example && yarn && cd ios && pod install`
3) Build Xcode

If this work, and your project doesn't, it is likely because the old Mapbox.framework is still referenced in your project. You need to make sure you properly unlink it before you add it again.

**Comment by cglacet** [comment] 2020-01-24 16:04
I tried to install the example, but `yarn` hangs (more than 2 hours): 

```
npm notice === Tarball Details ===
npm notice name:          @react-native-mapbox-gl/maps
npm notice version:       7.2.0
npm notice filename:      react-native-mapbox-gl-maps-7.2.0.tgz
...
Renaming react-native-mapbox-gl-maps-7.2.0.tgz
[1/4] 🔍  Resolving packages...
⡀ @react-native-mapbox-gl/maps@file:../react-native-mapbox-gl-maps.tgz
```

**Comment by makozlo-airship** [comment] 2020-01-24 16:09
I just tried running the example project and `yarn` is hanging for me as well:

```
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ node ./scripts/set_access_token.js && jetifier
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'accesstoken'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.<anonymous> (/Users/makozlo/Desktop/maps/example/scripts/set_access_token.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'accesstoken'
}```

**Comment by waris117** [comment] 2020-01-24 17:33
same issue i am also facing  in "@react-native-mapbox-gl/maps": "^7.2.0"
dyld: Library not loaded: @rpath/MapboxMobileEvents.framework/MapboxMobileEvents
  Referenced from: /Users/Waris/Library/Developer/CoreSimulator/Devices/C727A569-90E6-4660-B574-2290A01D541F/data/Containers/Bundle/Application/89128262-446E-4CAA-B19D-B2675EE9FA9B/Mechanican.app/Frameworks/Mapbox.framework/Mapbox
  Reason: image not found

**Comment by waris117** [comment] 2020-01-24 18:01
adding use_frameworks!, solves crash on launch but it cause issue for other pods

**Comment by kristfal** [comment] 2020-01-24 18:14
Good to hear it doesn’t crash.

Unfortunately Mapbox native iOS SDK now require use_frameworks, so there is
no way around it with pods afaik.

**Comment by systemlevel** [comment] 2020-01-25 01:48
Getting the same thing after upgrading to 7.2.0:

/Frameworks/Mapbox.framework/Mapbox
Reason: image not found

The use_frameworks! situation is very problematic for many applications including ours.  We cannot use many of the most popular libraries from Google including Crashlytics, Analytics, etc. etc.  when we have use_frameworks! in the podfile.

If this is required to use the new pod version of Mapbox SDK for iOS than I really concerned about how to make this work properly moving forward.

**Comment by kristfal** [comment] 2020-01-25 09:29
@systemlevel yeh, I totally get that. 

While it is an option, I'm not super stoked about going back to downloading the precompiled framework. The use_frameworks! requirement is a choice made by Mapbox upstream (as I see you noticed), and I hope they can provide a good pod-based experience that we can follow. I'd say we should do the following:

1) Push Mapbox into not requiring `use_frameworks!` and see if they can get out a change quickly
2) If option 1 doesn't happen shortly, I'll reverse back from pods to a static framework

**Comment by systemlevel** [comment] 2020-01-25 19:35
@kristfal Thank you! And thank you for the efforts in bringing the cocoapods over.  That sounds like a great plan moving forward.

**Comment by makozlo-airship** [comment] 2020-01-27 22:01
@kristfal I was having issues with the `use_frameworks!` requirement as well, has there been any update on whether that will be required moving forward?

**Comment by kristfal** [comment] 2020-01-27 22:13
No news from Mapbox. I’d Ideally like them to respond to https://github.com/mapbox/mapbox-gl-native-ios/issues/154 before we make a move. I suggest you subscribe to that ticket if you want to follow this. 

If I don’t hear anything by next week, I’ll get the workaround in place.

**Comment by cglacet** [comment] 2020-01-30 11:12
In the meantime, how could we (as end users) revert to previous version of the iOS SDK? Is it sufficient to rollback to a different version of react-native-mapbox-gl/maps? (which one?)

**Comment by kristfal** [comment] 2020-01-30 11:43
The interim solution if you can't use `use_frameworks!` is `npm install --save react-native-mapbox-gl/maps@7.0.9` / `yarn add react-native-mapbox-gl/maps@7.0.9`

**Comment by makozlo-airship** [comment] 2020-01-30 15:10
@kristfal when I try running `yarn add react-native-mapbox-gl/maps@7.0.9`, I get the following: 

```
An unexpected error occurred: "https://registry.yarnpkg.com/react-native-mapbox-gl%2fmaps: Request \"https://registry.yarnpkg.com/react-native-mapbox-gl%2fmaps\" returned a 405".
```

**Comment by kristfal** [comment] 2020-01-30 15:13
Forgot to add the @ before the install path. Updated code should work.

**Comment by makozlo-airship** [comment] 2020-01-30 15:16
@kristfal Just tried again, not working. Will your change take a few minutes to become available?

**Comment by kristfal** [comment] 2020-01-30 15:23
No, there is no delay. This works on my end:

```
--> yarn add @react-native-mapbox-gl/maps@7.0.9
yarn add v1.21.1
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @react-native-mapbox-gl/maps@7.0.9" has unmet peer dependency "prop-types@>=15.5.8".
warning " > @react-native-mapbox-gl/maps@7.0.9" has unmet peer dependency "react@^16.6.1".
warning " > @react-native-mapbox-gl/maps@7.0.9" has unmet peer dependency "react-native@>=0.57.6".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 8 new dependencies.
info Direct dependencies
└─ @react-native-mapbox-gl/maps@7.0.9
info All dependencies
├─ @mapbox/geo-viewport@0.4.0
├─ @mapbox/sphericalmercator@1.1.0
├─ @react-native-mapbox-gl/maps@7.0.9
├─ @turf/along@6.0.1
├─ @turf/bearing@6.0.1
├─ @turf/destination@6.0.1
├─ @turf/distance@6.0.1
└─ underscore@1.9.2
✨  Done in 103.57s.
```

If you get a different result, check your network connection, cache etc.

**Comment by makozlo-airship** [comment] 2020-01-30 15:37
Weird. Just ran it again and it installed fine. Thanks!

**Comment by joaodematejr** [comment] 2020-01-31 19:28
+1 :(

**Comment by afomic** [comment] 2020-02-06 16:58
@kristfal I tried the  new version(7.0.9) on android and i was getting this crash

` java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libhermes.so
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:738)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:591)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:529)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:484)
        at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
        at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:27)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:949)
        at java.lang.Thread.run(Thread.java:760)`

react-native version: 0.61.5

**Comment by Vednus** [comment] 2020-02-09 21:14
@afomic I had to go back to 7.0.8 to get things working on android. I forgot what the issue that 7.0.9 caused on Android, but there was something. I think it was hermes related.

**Comment by makozlo-airship** [comment] 2020-02-10 15:25
@kristfal I've been following this thread for a while (as well as [issue #154](https://github.com/mapbox/mapbox-gl-native-ios/issues/154)), and haven't seen any updates. I know you mentioned you would implement a workaround if you didn't hear back from Mapbox in a week or so, do you still have plans to do this?

**Comment by savv** [comment] 2020-02-11 16:14
> @kristfal when I try running `yarn add react-native-mapbox-gl/maps@7.0.9`, I get the following:
> 
> ```
> An unexpected error occurred: "https://registry.yarnpkg.com/react-native-mapbox-gl%2fmaps: Request \"https://registry.yarnpkg.com/react-native-mapbox-gl%2fmaps\" returned a 405".
> ```

It's better to go back to 7.0.10, because "updates the underlying Android SDK to version to 8.6.1 which fixes several crashes" according to:
https://github.com/react-native-mapbox-gl/maps/releases

**Comment by savv** [comment] 2020-02-11 17:19
I forked this branch at the point where the Android SDK was updated to 8.6.1, and then reverted the iOS SDK back to 5.5.0. In case you want to install that too:
yarn add https://github.com/savv/maps.git#063fa06e36a31985f972fc56a860edb1778ad78b

With the code above, I was able to get the app to start on both iOS and Android.

**Comment by mosef** [comment] 2020-02-19 16:26
This is still happening, has anyone figured out a fix?
(I've tried @savv 's solution but still no dice)

**Comment by systemlevel** [comment] 2020-02-19 17:20
Looks like there was some activity from Mapbox here: https://github.com/mapbox/mapbox-gl-native-ios/issues/154.  @julianrex is indicating no short-term action will be taken on use_frameworks issue. Wondering what the communities thoughts are on a path forward?

**Comment by ShaharyarMaroof** [comment] 2020-02-20 10:41
Hey, I just updated to 7.0.10 and I am getting the following error:
![image](https://user-images.githubusercontent.com/10959027/74926108-30dc6880-53f7-11ea-9ac5-64226aac7532.png)

I have the path to the pod for mapbox added to my Podfile. I removed my Pods folder and reinstalled the pods, but still getting this error. The pods installation was succesful.
Any idea why I am getting this?

**Comment by mfazekas** [comment] 2020-02-20 10:42
@ShaharyarMaroof there is an npm script that fetches the mapbox frmework into node_modules, it's likely that has failed

**Comment by ShaharyarMaroof** [comment] 2020-02-20 10:44
@mfazekas so how should I fix this? I can't ```use_frameworks!``` as my react-native version is below 0.61 currently.

**Comment by ShaharyarMaroof** [comment] 2020-02-20 10:55
@mfazekas got it fixed by reinstalling the node module, but now Im also getting the  ```@rpath/MapboxMobileEvents.framework/MapboxMobileEvents``` error. So I think I should revert to 7.0.9 then.

**Comment by tr3v3r** [comment] 2020-02-21 21:08
I have `@rpath/MapboxMobileEvents.framework/MapboxMobileEvents` error on version 7.0.9.

**Comment by yacineblr** [comment] 2020-03-06 16:36
I have same error with 7.2.0 version, have you found a solution please?

**Comment by TasosTsaou** [comment] 2020-03-07 09:47
Any news on this guys? 7.20 is still crashing on startup

**Comment by makozlo-airship** [comment] 2020-03-09 15:00
Having the same issue with `7.2.0` here. Crashes on startup on Android.

**Comment by ShaharyarMaroof** [comment] 2020-03-09 15:01
I reverted to 7.0.9 to get it work on both platforms.

**Comment by ferdicus** [comment] 2020-03-09 16:50
To everyone having issues with Android, could you please try to reproduce on `/example`?

**Comment by kk12837** [comment] 2020-03-10 07:52
Any updates?

It still crashes on start on real iPhone.

**Comment by mfazekas** [comment] 2020-03-10 15:12
There is PR #714 which offers a workaround for `use_frameworks!` please test. But it will not solve other issues in this thread.

**Comment by kk12837** [comment] 2020-03-11 01:19
> I reverted to 7.0.9 to get it work on both platforms.

on real devices?

**Comment by kk12837** [comment] 2020-03-11 01:20
> I reverted to 7.0.9 to get it work on both platforms.

on real devices?

**Comment by ShaharyarMaroof** [comment] 2020-03-11 04:33
@kk12837 yes.

**Comment by mfazekas** [comment] 2020-03-11 08:04
I'm closing this as there are multiple issues here. 
8.0.0 can be used without `use_frameworks!` see #714

**Closed by mfazekas** 2020-03-11 08:04 UTC
Labels: upstream
