### ISSUE TITLE
Axios request get blocked 

### ISSUE THREAD

**Issue by DirkDiggler31** [react-native-mapbox-gl/maps#1474] opened 2021-07-27 12:31 UTC
Hello, i have an app which is working fine. But if i install the @react-native-mapbox-gl/maps with a version >7.2.0, my axios request is blocked and return "network error" this request is called in the login, before any other request. I really don't get it,if i delete the dependency everything works fine. Here's my code for my request :

```
 static async initDonneesAccueil(listeInit) {
    let username = listeInit[0];
    let password = listeInit[1];

    let headersPost = {
      "Content-Type": "application/x-www-form-urlencoded"
    }
       
    return await axios.post(global.link, qs.stringify({ 
      tokenMobile: null,
      keyConnect: null,
      formData : `username=${listeInit[0]}&password=${listeInit[1]}`,
      methode :  "initDonneesAccueil",
      etat: "init", 
  }),
   headersPost).then((res) => {
   
     if (res.data.status) {
       console.log(res.data)
       AsyncStorage.setItem("tokenMobile", res.data.tokenmsg);
       AsyncStorage.setItem("KeyConnect", res.data.keyconnect)
      return res.data.tokenmsg
     }
      else { Alert.alert( "Erreur Identifiants")}
    })
    .catch(err => console.log(err))

  }]

```
Thank you for your answer, have a nice day.

**Version**

    Platform: Android
    Platform OS: Android 9
    Device: Huawei P Smart
    Emulator/ Simulator: same problem
    Dev OS: Windows 10
    react-native-mapbox-gl Version: 8.0.0
    React Native Version: 0.64.1

**Comment by ferdicus** [comment] 2021-07-30 13:35
what about plain old `fetch` requests?

**Comment by DirkDiggler31** [comment] 2021-07-30 14:48
Yes it doesn't work neither, it may be because of my extranet's company, but i don't understand why it's working in version 7.2.0 without any issues.

**Comment by ferdicus** [comment] 2021-07-30 15:11
I'm sorry, but you're the only one reporting this :(   
Maybe you can create a reproducible setup with our `/example` app we could test with? 

Thanks

**Comment by jarrodyellets** [comment] 2021-08-03 13:43
I too am getting this issue, only in Android tho.  iOS works fine.  As with the original poster, it happens on the initial login...with a valid user name and password, we get the ` [Error: Network Error]` error.  Without the library, it works ok. I'm going to try and recreated it with `/example` to test with.

**Comment by aminsaedi** [comment] 2021-08-04 10:38
I have same problem, any solution?

**Comment by ferdicus** [comment] 2021-08-06 10:37
I'm marking this as upstream, I tried with the current `master` on the example application and was unable to reproduce this issue.

test code:
```
const getJokes = async () => {
  const jokes = await fetch('https://official-joke-api.appspot.com/jokes/ten');
  return await jokes.json();
}

const jokes = await getJokes();
console.log('>>>>>>', jokes);
```

which returned correct results 


I also tried with the endpoint mentioned in issue https://github.com/facebook/react-native/issues/29196 by @jarrodyellets 

also works


without a proper repo and fully filled out specs of the issue template, there is nothing more we can do from our side


closing this - we can reopen if new info emerges

**Closed by ferdicus** 2021-08-06 10:37 UTC
Labels: upstream, Android, Needs: Repro, Needs: Author Feedback

**Comment by zholmes1** [comment] 2021-08-07 17:04
@ferdicus Consider that this is the same issue that I encountered with the `okhttp` versions being out of sync.

**Comment by ferdicus** [comment] 2021-08-08 11:54
> @ferdicus Consider that this is the same issue that I encountered with the `okhttp` versions being out of sync.

you heard the man - please try with `master` all :)
