### ISSUE TITLE
Xcode build failed

### ISSUE THREAD

**Issue by designervoid** [react-native-mapbox-gl/maps#1304] opened 2021-04-05 18:21 UTC
**Describe the bug**  
I can run my app in debug mode on device and simulator with `npx react-native run-ios`.
I can create archives of my app and send them in Test Flight and AppStore.
I can build with detox-cli my debug and release mode iOS app.
But xCode12 run on device or simulator build failed with that error:
```zsh
Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/maximchernyshov/Desktop/project/frontend/ios/Pods/Mapbox-iOS-SDK/dynamic/Mapbox.framework/Mapbox' for architecture arm64
```

**To Reproduce**  
Build project with `"@react-native-mapbox-gl/maps": "^8.2.0-beta1",` in `xCode` on `iPhone11`, `iOS 14.4`

**Additional Context**
`npx react-native info`
```
maximchernyshov@MacBook-Pro-Maxim frontend % npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 739.18 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6953283
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 13.0.2 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.3 => 0.63.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by ferdicus** [comment] 2021-04-05 19:31
Can you please try the `example` project in the repo and report back - thanks

**Comment by designervoid** [comment] 2021-04-05 20:38
@ferdicus 
build settings:
![image](https://user-images.githubusercontent.com/43455658/113623911-aa6cff80-9667-11eb-94a3-f4cb0e68f099.png)
my scheme:
![image](https://user-images.githubusercontent.com/43455658/113624200-ffa91100-9667-11eb-91f8-59a5606d5c18.png)

**Comment by designervoid** [comment] 2021-04-05 20:41
my mapbox component:
```
import MapboxGL from '@react-native-mapbox-gl/maps';
import Config from "react-native-config";

MapboxGL.setAccessToken(Config.MAPBOX_API_KEY);

const Map = observer(() => {
  const cities = {
    moscow: [37.618423, 55.751244],
  };
  const [coordinates] = useState(cities.moscow);

  return (
    <>
      <MapboxGL.MapView
        style={
          flex: 1,
        }}>
        <MapboxGL.UserLocation />
        <MapboxGL.Camera zoomLevel={8} centerCoordinate={coordinates} />
      </MapboxGL.MapView>
    </>
  );
});
````

**Comment by mfazekas** [comment] 2021-04-06 04:57
@designervoid sounds like duplicate of https://github.com/react-native-mapbox-gl/maps/issues/1031 is this an M1 Mac?!

**Comment by designervoid** [comment] 2021-04-06 10:00
no, i have macbook pro 19 (16 inch) with intel i7

**Comment by designervoid** [comment] 2021-04-08 16:56
answer of @questionsrvdende in thread
```
I get this error when building for the simulator as release instead of debug.

Solution is to go to Product > Scheme > Edit Scheme

Set Build Configuration to Debug Tick Debug Executable
```

**Comment by designervoid** [comment] 2021-04-08 17:06
Now after changing `Architectures` field to `x86_64` my app working on simulator. Now I can run my app throught xcode on simulator.
![image](https://user-images.githubusercontent.com/43455658/114067647-b940f580-98a5-11eb-8a47-988f1835fab1.png)

**Comment by ferdicus** [comment] 2021-04-09 11:43
so all good, yes? closing this

**Closed by ferdicus** 2021-04-09 11:43 UTC
Labels: Needs: Author Feedback

**Comment by noway** [comment] 2021-04-10 02:14
You can encounter this error on both x86 and Apple Silicon. On x86 it's solved with the EXCLUDE_ARCH build setting. On Apple Silicon, there's still no fix.

Let's keep this issue scoped to x86 and close it.
