### ISSUE TITLE
Cannot call map method (showAttribution) - gives this._runNativeCommand is not a function

### ISSUE THREAD

**Issue by dancherb** [react-native-mapbox-gl/maps#1409] opened 2021-06-17 09:18 UTC
**Describe the bug**  

Cannot run _showAttribution_ method on the map ref in a functional component. May also apply to other methods.

```
import React, { useRef } from 'react';
import { TouchableOpacity } from 'react-native';
import MapboxGL from '@react-native-mapbox-gl/maps';

export default function Map(p) {
    const mapRef = useRef()
    
    return (
        <TouchableOpacity onPress={mapRef?.current?.showAttribution}>
            <MapboxGL.MapView 
                ref={mapRef}
                attributionEnabled={false}
            />
        </TouchableOpacity>
    )
}
```

**Expected behavior**  
Opens attribution menu, as when you click the default 'i'.

**Actual behavior**  
Gives the following error:

`this._runNativeCommand is not a function. (In 'this._runNativeCommand('showAttribution', this._nativeRef)', 'this._runNativeCommand' is undefined)`

**Versions (please complete the following information):**  
 - Platform: Android
 - Platform OS: Android 8
 - Device: Pixel 2
 - Emulator/ Simulator: Yes
 - Dev OS: Win10 Professional
 - react-native-mapbox-gl Version: 8.2.0
 - Mapbox GL version: default
 - React Native Version: 0.64.0

**Update**  

I've created a fresh React Native project (latest at 0.64.2) using the latest master from this package. I'm still experiencing issues with refs, where the ref is not populated. 

`react-native init MapTest`
`npm i -S https://github.com/react-native-mapbox-gl/maps`

app.js:
```
import React, {useRef} from 'react';
import type {Node} from 'react';
import Mapbox from '@react-native-mapbox-gl/maps';
import {View} from 'react-native';

Mapbox.setAccessToken(
  'pk.xxx'
);

const App: () => Node = () => {
  const mapRef = useRef();

  console.log('mapRef =', mapRef);
  
  return (
    <View style={{flex: 1}}>
      <Mapbox.MapView ref={mapRef} style={{width: '100%', height: '100%'}} />
    </View>
  );
};

export default App;
```

The map loads, but `mapRef = {"current": undefined}` is logged and no methods are accessible.

Interestly, if you hit CTRL+S on App.js, this causes the app to fast refresh and then mapRef.current methods become available. But they aren't available during normal use of the app.

**Comment by ferdicus** [comment] 2021-06-18 14:33
hi there,  
sorry, however I can not reproduce this within our `/example` project on the `master` branch. 

Here the steps I used:
* build our `example` project
* on this screen `example/src/examples/Map/ShowMap.tsx`
* alter these lines:
https://github.com/react-native-mapbox-gl/maps/blob/0e173c757c754ca6b3710fab88fe37b7b2014995/example/src/examples/Map/ShowMap.tsx#L29-L31
* to include `mapRef?.current?.showAttribution()`
* principle is the same, on button press `showAttribution` is called

Please watch the attached video showing the result



https://user-images.githubusercontent.com/26439946/122577302-eacaff80-d052-11eb-9792-fc99f1f1aaef.mp4

**Comment by dancherb** [comment] 2021-06-28 11:54
I've created a fresh React Native project (latest at 0.64.2) and am still experiencing issues with refs, where the ref is not populated. 

`react-native init MapTest`
`npm i -S https://github.com/react-native-mapbox-gl/maps`

app.js:
```
import React, {useRef} from 'react';
import type {Node} from 'react';
import Mapbox from '@react-native-mapbox-gl/maps';
import {View} from 'react-native';

Mapbox.setAccessToken(
  'pk.xxx'
);

const App: () => Node = () => {
  const mapRef = useRef();

  console.log('mapRef =', mapRef);
  
  return (
    <View style={{flex: 1}}>
      <Mapbox.MapView ref={mapRef} style={{width: '100%', height: '100%'}} />
    </View>
  );
};

export default App;
```

The map loads, but `mapRef = {"current": undefined}` is logged and no methods are accessible.

Interestly, if you hit CTRL+S on App.js, this causes the app to fast refresh and then mapRef.current methods become available. But they aren't available during normal use of the app.

**Comment by ferdicus** [comment] 2021-08-06 15:33
Any update on this @dancherb?
I'm inclined to close this, due to the fact, that no one else reported this + I can use mapRefs in my project just fine.

**Comment by ferdicus** [comment] 2021-09-24 12:47
closing due to inactivity

**Closed by ferdicus** 2021-09-24 12:47 UTC
Labels: Needs: Author Feedback

**Comment by Kailo-B** [comment] 2022-08-17 20:15
I am still getting this exact issue, has any solution been found?

**Comment by swey** [comment] 2022-11-06 12:20
@ferdicus The problem is that the mapbox v10 implementation is missing the method

https://github.com/rnmapbox/maps/blob/main/ios/RCTMGL-v10/RCTMGLMapViewManager.m
vs.
https://github.com/rnmapbox/maps/blob/main/ios/RCTMGL/RCTMGLMapViewManager.m#L292
