### ISSUE TITLE
Getting warning Message while installing app.

### ISSUE THREAD

**Issue by saurabh-nandan** [react-native-mapbox-gl/maps#409] opened 2019-09-24 14:30 UTC
**Describe the bug**
warn The following packages use deprecated "rnpm" config that will stop working from next release:
  - @react-native-mapbox-gl/maps: https://github.com/react-native-mapbox-gl/maps#readme
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

**Comment by kristfal** [comment] 2019-09-24 14:38
Duplicate of #391. Closing.

**Closed by kristfal** 2019-09-24 14:38 UTC
