### ISSUE TITLE
Error : :@react-native-mapbox-gl_maps:javaPreCompileDebug

### ISSUE THREAD

**Issue by alikhazeni** [react-native-mapbox-gl/maps#594] opened 2020-01-02 07:35 UTC
install react-native-mapbox-gl when run project in android emulator has Error  
how resolve it 
Error : 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-mapbox-gl_maps:javaPreCompileDebug'.
> Could not resolve all files for configuration ':@react-native-mapbox-gl_maps:debugCompileClasspath'.
   > Could not find vectordrawable.jar (androidx.vectordrawable:vectordrawable:1.0.1).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable/1.0.1/vectordrawable-1.0.1.jar
   > Could not find legacy-support-core-utils.jar (androidx.legacy:legacy-support-core-utils:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-core-utils/1.0.0/legacy-support-core-utils-1.0.0.jar

**Comment by ferdicus** [comment] 2020-01-02 09:24
can you please try with the `example` folder.
Just built it successfully myself.

**Comment by inpendio** [comment] 2020-01-05 11:23
I have same error. Best part, it used to compile, but something broke ( nothing changed with project it self)

**Comment by ferdicus** [comment] 2020-01-05 16:10
Can you please follow these steps and build again.


# Errors when building the app
## Start with a clean slate

### Remove all traces of previous builds, by following these steps:

    in <PROJECT_ROOT>/android run ./gradlew clean
    in <PROJECT_ROOT> run rm -rf node_modules (removes node modules)
    in <PROJECT_ROOT> run rm -rf ~/.gradle/caches (removes all cached native android deps)
    in <PROJECT_ROOT> run rm -rf android/app/build (cached build artifacts from previous runs)

This leaves a clean start. 


### Stop gradle deamon
If `react-native run-android` won't pass, `cd` to `android/` and run `./gradlew --stop`. 
This will stop all gradle deamons running which is sometimes the cause.

**Comment by mfazekas** [comment] 2020-02-21 06:07
I'm closing this, please provide full steps to reproduce (from `react-native init`).

**Closed by mfazekas** 2020-02-21 06:07 UTC
