### ISSUE TITLE
iOS: Unable to resolve module `.utils/AnimatedPoint` after upgrading to version 8.2.0-beta2

### ISSUE THREAD

**Issue by nemanjagajic** [react-native-mapbox-gl/maps#1406] opened 2021-06-16 13:21 UTC
After upgrading the package version to `8.2.0-beta2` from `7.2.0` and trying to run the application on a simulator, an app crashes with the message "Unable to resolve module `.utils/AnimatedPoint` from `node_modules/@react-native-mapbox-gl/maps/javascript/index.js`".

I've also tried putting `$ReactNativeMapboxGLIOSVersion = '~> 6.3'` to the Podfile, but this error happened both with 6.3.0 and 5.9.0 mapbox sdk

**To Reproduce**  
Upgrade version to 8.2.0-beta2 and try to run the app

**Expected behavior**  
The application should work normally

**Screenshots**  
<img width="396" alt="Screenshot 2021-06-16 at 15 15 18" src="https://user-images.githubusercontent.com/18125186/122225804-0e107600-cebe-11eb-9afc-1a25d785ce57.png">

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: iOS 14.3
 - Device: iPhone 11 Pro
 - Emulator/ Simulator: yes
 - react-native-mapbox-gl Version [8.2.0-beta2]
 - Mapbox GL version [6.3.0 and 5.9.0]
 - React Native Version [0.63.4]

**Additional context**  
I've seen that folder structure has changed, and `AnimatedPoint` has been moved to the `animated` folder, but I cannot find anywhere in the code that `.utils/AnimatedPoint` is trying to be imported

**Comment by ferdicus** [comment] 2021-06-18 13:08
Did you try `MapboxGL.AnimatedPoint` ?
https://github.com/react-native-mapbox-gl/maps/blob/f7006102db37be02a8214713aefe9682ac3fa6e2/javascript/index.js#L109

**Comment by hexadecy** [comment] 2021-06-19 13:26
I remember to have this issue, looks like a cache cleanup.
https://www.instamobile.io/react-native-tutorials/full-clean-react-native-project/

**Comment by nemanjagajic** [comment] 2021-06-21 13:31
As @hexadecy pointed out, it seems like it was a cache issue and started working on its own, so I will close this issue. Thank you both!

**Comment by nemanjagajic** [comment] 2021-06-22 15:07
It has actually started happening again, and also cleaning the whole cache didn't help. It seems like it might be some kind of cache issue, but I will reopen it as there is still no concrete solution

**Comment by nemanjagajic** [comment] 2021-06-22 17:25
Also, it might be helpful that I receive this error in Xcode when starting an app, even tho it builds and launches successfully. So it might be some configuration issue that has occurred when upgrading to the new version
<img width="261" alt="Screenshot 2021-06-22 at 19 22 05" src="https://user-images.githubusercontent.com/18125186/122971254-846a1800-d397-11eb-9cc7-625b415eb342.png">

**Comment by ferdicus** [comment] 2021-06-27 11:37
Please reproduce with `example` app and paste code that reproduces your issue.

**Comment by ferdicus** [comment] 2021-08-06 15:35
Closing due to lack of reply. 
Let me know if this is still happening for you

**Closed by ferdicus** 2021-08-06 15:35 UTC
Labels: Needs: Author Feedback
