### ISSUE TITLE
iOS Archive build success, but not able to export

### ISSUE THREAD

**Issue by yudiz-vipul** [react-native-mapbox-gl/maps#1224] opened 2021-02-18 10:21 UTC
I have used the following versions react native and map box version:
```
"react-native": "0.63.2",
"@react-native-mapbox-gl/maps": "^8.1.0",
"@react-native-firebase/analytics": "^10.8.0",
"@react-native-firebase/app": "^10.8.0",
"@react-native-firebase/crashlytics": "^10.8.0",
"@react-native-firebase/dynamic-links": "^10.7.0",
"@react-native-firebase/messaging": "^10.8.0",
```

For the cocoa pod, I have used the latest cocoa pod version 1.10.1 and it is must be required for react native firebase library.
![Screenshot 2021-02-18 at 3 48 48 PM](https://user-images.githubusercontent.com/45070224/108342584-f7545e00-7200-11eb-8e81-76fafe8139e6.png)

While I am tried to making build and export at that time, build an archive successfully but not able to export!!

**Comment by muxton21** [comment] 2021-02-18 17:02
I have been having this issue for the past 4 days and have been unable to resolve. See this [link](https://github.com/react-native-mapbox-gl/maps/issues/1097) to see if it is any help. I cannot downgrade my cocoa pods version as other pods require a more up to date version than 1.9.3 and have tried downgrading Mapbox to '8.1.0-rc.4' as suggested there with no luck. This is a very frustrating issue.

**Comment by muxton21** [comment] 2021-02-18 18:29
As a follow up to my previous comment, I tried creating a brand new react-native project without Mapbox and the release is created successfully. I then added Mapbox '8.0.0' (thinking a lower version may work) via yarn and .xarchive produces message 'The archive may be corrupt or unreadable.' Cocoapods version '1.10.1'

**Comment by muxton21** [comment] 2021-02-18 20:03
In the end, I managed to solve this by downgrading Cocoapods to version '1.9.3'

**Comment by mfazekas** [comment] 2021-03-02 13:54
Duplicate of #1097

**Closed by mfazekas** 2021-03-02 13:54 UTC
