### ISSUE TITLE
Build on real device

### ISSUE THREAD

**Issue by kk12837** [react-native-mapbox-gl/maps#712] opened 2020-03-10 07:50 UTC
Iphone: IOS 13.3.1
project: react-native-mapbox-gl/maps@7.0.9

step to reproduce:
cd example
npm install
cd ios
pod install
open RNMapboxGLExample.xcodeproj
open xcode (set up bundle / signing) and run.

Successfully install on my iPhone.

But when I open the app, it crashes and close immediately. 

Can anyone give me a hand?

Thanks

**Comment by ferdicus** [comment] 2020-03-10 07:54
duplicate of #635

**Closed by ferdicus** 2020-03-10 07:54 UTC
